name = "FixedPointSinCosApproximations"
uuid = "aedcc28f-63b5-4046-b467-b09cfa7c8db7"
authors = ["Soeren Zorn"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
