name = "FixedPointSinCosApproximations"
uuid = "aedcc28f-63b5-4046-b467-b09cfa7c8db7"
authors = ["Soeren Zorn"]
version = "0.2.2"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
DocStringExtensions = "0.7, 0.8, 0.9"
SIMD = "3"
julia = "1.6"

[extras]
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SIMD", "Test"]
