name = "FixedPointSinCosApproximations"
uuid = "aedcc28f-63b5-4046-b467-b09cfa7c8db7"
authors = ["Soeren Zorn"]
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"

[compat]
DocStringExtensions = "0.6, 0.7, 0.8"
LoopVectorization = "0.8.1 - 0.8"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
